=== BryceCanyonCounty/rdr3-nativedb-data/schemas/controls.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1676761119.json", 
	"title": "Root", 
	"type": "array",
	"default": [],
	"items":{
		"$id": "#root/items", 
		"title": "Items", 
		"type": "object",
		"required": [
			"hash",
			"name",
			"key",
			"gameversion"
		],
		"properties": {
			"hash": {
				"$id": "#root/items/hash", 
				"title": "Hash", 
				"type": "string",
				"default": "",
				"examples": [
					"0x3D23549A"
				],
				"pattern": "^.*$"
			},
			"name": {
				"$id": "#root/items/name", 
				"title": "Name", 
				"type": "string",
				"default": "",
				"examples": [
					"INPUT_FRONTEND_RIGHT_AXIS_X"
				],
				"pattern": "^.*$"
			},
			"key": {
				"$id": "#root/items/key", 
				"title": "Key", 
				"type": "string",
				"default": "",
				"examples": [
					"["
				],
				"pattern": "^.*$"
			},
			"gameversion": {
				"$id": "#root/items/gameversion", 
				"title": "Gameversion", 
				"type": ["number", "string"],
				"examples": [
					1207.8
				],
				"default": 0.0
			},
            "commonuse": {
				"$id": "#root/items/commonuse", 
				"title": "CommonUse", 
				"type": "boolean",
				"default": false,
				"examples": [
					false
				]
			}
		}
	}

}

=== BryceCanyonCounty/rdr3-nativedb-data/controls/controls.json
[
    {
      "hash": "0x3D23549A",
      "name": "INPUT_FRONTEND_RIGHT_AXIS_X",
      "key": "[",
      "gameversion": 1207.8
    },
    {
      "hash": "0x430593AA",
      "name": "INPUT_SNIPER_ZOOM_OUT_ONLY",
      "key": "[",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x7ABC6A66",
      "name": "INPUT_SNIPER_ZOOM",
      "key": "[",
      "gameversion": 1207.8
    },
    {
      "hash": "0xA5BDCD3C",
      "name": "INPUT_SNIPER_ZOOM_IN_ONLY",
      "key": "]",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x52D29063",
      "name": "INPUT_EMOTE_TWIRL_GUN_VAR_B",
      "key": "BUTTON 1",
      "gameversion": 1311.12
    },
    {
      "hash": "0xE6F612E4",
      "name": "INPUT_SELECT_QUICKSELECT_SIDEARMS_LEFT",
      "key": "BUTTON 1",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0xF311100C",
      "name": "INPUT_EMOTE_DANCE",
      "key": "BUTTON 1 (when actions menu active)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x1CE6D9EB",
      "name": "INPUT_SELECT_QUICKSELECT_DUALWIELD",
      "key": "BUTTON 2",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0x6990BDDF",
      "name": "INPUT_EMOTE_TWIRL_GUN_VAR_A",
      "key": "BUTTON 2",
      "gameversion": 1311.12
    },
    {
      "hash": "0x72BAD5AA",
      "name": "INPUT_EMOTE_GREET",
      "key": "BUTTON 2 (when actions menu active)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x4F49CC4C",
      "name": "INPUT_SELECT_QUICKSELECT_SIDEARMS_RIGHT",
      "key": "BUTTON 3",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0xAE69478F",
      "name": "INPUT_EMOTE_TWIRL_GUN_VAR_D",
      "key": "BUTTON 3",
      "gameversion": 1311.12
    },
    {
      "hash": "0x661857B3",
      "name": "INPUT_EMOTE_COMM",
      "key": "BUTTON 3 (when actions menu active)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x8F9F9E58",
      "name": "INPUT_SELECT_QUICKSELECT_UNARMED",
      "key": "BUTTON 4",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0x470DC190",
      "name": "INPUT_EMOTE_TAUNT",
      "key": "BUTTON 4 (when actions menu active)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xAB62E997",
      "name": "INPUT_SELECT_QUICKSELECT_MELEE_NO_UNARMED",
      "key": "BUTTON 5",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0xA1FDE2A6",
      "name": "INPUT_SELECT_QUICKSELECT_SECONDARY_LONGARM",
      "key": "BUTTON 6",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0xB03A913B",
      "name": "INPUT_SELECT_QUICKSELECT_THROWN",
      "key": "BUTTON 7",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0x42385422",
      "name": "INPUT_SELECT_QUICKSELECT_PRIMARY_LONGARM",
      "key": "BUTTON 8",
      "gameversion": 1311.12,
      "commonuse": true
    },
    {
      "hash": "0x7065027D",
      "name": "INPUT_MOVE_LEFT_ONLY",
      "key": "A",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x877F1027",
      "name": "INPUT_FRONTEND_NAV_LEFT",
      "key": "A",
      "gameversion": 1207.8
    },
    {
      "hash": "0x86D773F6",
      "name": "INPUT_HORSE_MOVE_LEFT_ONLY",
      "key": "A (when driving horse)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x07D1654C",
      "name": "INPUT_VEH_CAR_TURN_LEFT_ONLY",
      "key": "A (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x198AFC64",
      "name": "INPUT_VEH_DRAFT_TURN_LEFT_ONLY",
      "key": "A (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x5BED7C91",
      "name": "INPUT_VEH_BOAT_TURN_LEFT_ONLY",
      "key": "A (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x9DF54706",
      "name": "INPUT_VEH_MOVE_LEFT_ONLY",
      "key": "A (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x4CC0E2FE",
      "name": "INPUT_OPEN_SATCHEL_MENU",
      "key": "B",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x5966D52A",
      "name": "INPUT_OPEN_SATCHEL_HORSE_MENU",
      "key": "B",
      "gameversion": 1207.8
    },
    {
      "hash": "0xD3ECF82F",
      "name": "INPUT_SHOP_BOUNTY",
      "key": "B",
      "gameversion": 1311.12
    },
    {
      "hash": "0xEED15F18",
      "name": "INPUT_SWITCH_FIRING_MODE",
      "key": "B",
      "gameversion": 1311.12
    },
    {
      "hash": "0x156F7119",
      "name": "INPUT_FRONTEND_CANCEL",
      "key": "BACKSPACE",
      "gameversion": 1207.8
    },
    {
      "hash": "0x308588E6",
      "name": "INPUT_GAME_MENU_CANCEL",
      "key": "BACKSPACE",
      "gameversion": 1207.8
    },
    {
      "hash": "0x5B48F938",
      "name": "INPUT_FRONTEND_RRIGHT",
      "key": "BACKSPACE",
      "gameversion": 1207.8
    },
    {
      "hash": "0x8E90C7BB",
      "name": "INPUT_QUIT",
      "key": "BACKSPACE",
      "gameversion": 1207.8
    },
    {
      "hash": "0xE9094BA0",
      "name": "INPUT_MINIGAME_QUIT",
      "key": "BACKSPACE",
      "gameversion": 1207.8
    },
    {
      "hash": "0x9959A6F0",
      "name": "INPUT_LOOK_BEHIND",
      "key": "C",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x81280569",
      "name": "INPUT_HORSE_LOOK_BEHIND (while driving horse)",
      "key": "C",
      "gameversion": ""
    },
    {
      "hash": "0xA6C67243",
      "name": "INPUT_CINEMATIC_CAM_CHANGE_SHOT",
      "key": "C",
      "gameversion": 1311.12
    },
    {
      "hash": "0xD8CF0C95",
      "name": "INPUT_CREATOR_RS",
      "key": "C",
      "gameversion": 1311.12
    },
    {
      "hash": "0xCAE9B017",
      "name": "INPUT_VEH_LOOK_BEHIND",
      "key": "C (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xA6C67243",
      "name": "INPUT_CINEMATIC_CAM_CHANGE_SHOT",
      "key": "C (when in cinematic mode camera)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xD8CF0C95",
      "name": "INPUT_CREATOR_RS",
      "key": "C (when in cinematic mode camera)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x811F4A1A",
      "name": "INPUT_SECONDARY_SPECIAL_ABILITY_SECONDARY",
      "key": "CAPS LOCK",
      "gameversion": 1207.8
    },
    {
      "hash": "0xCEE12B50",
      "name": "INPUT_SPECIAL_ABILITY",
      "key": "CAPS LOCK",
      "gameversion": 1207.8
    },
    {
      "hash": "0x08BD758C",
      "name": "INPUT_FRONTEND_NAV_RIGHT",
      "key": "D",
      "gameversion": 1207.8
    },
    {
      "hash": "0x4D8FB4C1",
      "name": "INPUT_MOVE_LR",
      "key": "D",
      "gameversion": 1207.8
    },
    {
      "hash": "0xB4E465B4",
      "name": "INPUT_MOVE_RIGHT_ONLY",
      "key": "D",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0xF1111E4A",
      "name": "INPUT_SCRIPTED_FLY_LR",
      "key": "D",
      "gameversion": 1207.8
    },
    {
      "hash": "0xFB56DD5B",
      "name": "INPUT_FRONTEND_AXIS_X",
      "key": "D",
      "gameversion": 1207.8
    },
    {
      "hash": "0x3224BC55",
      "name": "INPUT_FRONTEND_SCROLL_AXIS_X",
      "key": "D",
      "gameversion": 1311.12
    },
    {
      "hash": "0x3F4DC0EF",
      "name": "INPUT_CREATOR_DELETE",
      "key": "DELETE",
      "gameversion": 1207.8
    },
    {
      "hash": "0x4AF4D473",
      "name": "INPUT_FRONTEND_DELETE",
      "key": "DELETE",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x05CA7C52",
      "name": "INPUT_FRONTEND_DOWN",
      "key": "DOWN ARROW",
      "gameversion": 1207.8,
      "commonuse": true
    },
    {
      "hash": "0x4403F97F",
      "name": "INPUT_GAME_MENU_DOWN",
      "key": "DOWN ARROW",
      "gameversion": 1207.8
    },
    {
      "hash": "0x78114AB3",
      "name": "INPUT_FRONTEND_NAV_DOWN",
      "key": "DOWN ARROW",
      "gameversion": 1207.8
    },
    {
      "hash": "0x21651AD6",
      "name": "INPUT_FRONTEND_SCROLL_AXIS_Y",
      "key": "DOWN ARROW",
      "gameversion": 1311.12
    },
    {
      "hash": "0x126796EB",
      "name": "INPUT_HORSE_MOVE_LR",
      "key": "D (when driving horse)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x7E6B8612",
      "name": "INPUT_HORSE_MOVE_RIGHT_ONLY",
      "key": "D (when driving horse)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x3BD38D43",
      "name": "INPUT_VEH_CAR_TURN_LR",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x5E371EA7",
      "name": "INPUT_VEH_DRAFT_TURN_RIGHT_ONLY",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x6E3C3649",
      "name": "INPUT_VEH_CAR_TURN_RIGHT_ONLY",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x97A8FD98",
      "name": "INPUT_VEH_MOVE_RIGHT_ONLY",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xA7DFAE8A",
      "name": "INPUT_VEH_DRAFT_TURN_LR",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xD8DFCAB3",
      "name": "INPUT_VEH_BOAT_TURN_LR",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xF1E2852C",
      "name": "INPUT_VEH_MOVE_LR",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0xF9780DFB",
      "name": "INPUT_VEH_BOAT_TURN_RIGHT_ONLY",
      "key": "D (when driving vehicle)",
      "gameversion": 1207.8
    },
    {
      "hash": "0x018C47CF",
      "name": "INPUT_MELEE_GRAPPLE_CHOKE",
      "key": "E",
      "gameversion": 1207.8
    },
    {
      "hash": "0x110AD1D2",
      "name": "INPUT_GAME_MENU_TAB_RIGHT",
      "key": "E",
      "gameversion": 1207.8
    },
    {
